"""Domain models, enums, and exceptions for AutoForm."""

from autoform.domain.enums import (
    ConfidenceLevel,
    FieldType,
    FillStatus,
    LabelSource,
    MatchMethod,
    Platform,
)
from autoform.domain.exceptions import (
    AutoFormError,
    BrowserError,
    BrowserLaunchError,
    BrowserNavigationError,
    BrowserTimeoutError,
    CaptchaDetectedError,
    ElementNotFoundError,
    ElementNotInteractableError,
    FillError,
    FillVerificationError,
    FormAnalysisError,
    MappingError,
    NoFieldsDetectedError,
    NoMappingFoundError,
    ProfileError,
    ProfileNotFoundError,
    SafetyCheckError,
    UnsupportedPlatformError,
)
from autoform.domain.models import (
    FieldMapping,
    FieldOption,
    FieldValidation,
    FillFieldResult,
    FillResult,
    FormField,
    FormSchema,
    FormSection,
    MatchCandidate,
    SubmitResult,
    UserProfile,
)

__all__ = [
    # Enums
    "ConfidenceLevel",
    "FieldType",
    "FillStatus",
    "LabelSource",
    "MatchMethod",
    "Platform",
    # Models
    "FieldMapping",
    "FieldOption",
    "FieldValidation",
    "FillFieldResult",
    "FillResult",
    "FormField",
    "FormSchema",
    "FormSection",
    "MatchCandidate",
    "SubmitResult",
    "UserProfile",
    # Exceptions
    "AutoFormError",
    "BrowserError",
    "BrowserLaunchError",
    "BrowserNavigationError",
    "BrowserTimeoutError",
    "CaptchaDetectedError",
    "ElementNotFoundError",
    "ElementNotInteractableError",
    "FillError",
    "FillVerificationError",
    "FormAnalysisError",
    "MappingError",
    "NoFieldsDetectedError",
    "NoMappingFoundError",
    "ProfileError",
    "ProfileNotFoundError",
    "SafetyCheckError",
    "UnsupportedPlatformError",
]
